disabled = false
languageCode = 'en-US'
languageName = 'English'
title = 'Lia Brüggemann' # This will go in the Header as well
copyright = """Made with [Hugo](https://gohugo.io/) & [Magnolia](https://github.com/ololiuhqui/magnolia-free-hugo-theme) by [Myself](https://github.com/BlyDoesCoding)\n
 Original Theme licensed under [MIT license](https://github.com/ololiuhqui/magnolia-free-hugo-theme/blob/main/LICENSE.md) 📄""" # Please leave this here to give me and the tools i used some credit for the work, or BuyMeACoffee and change or remove the copyrightlink below :)
contentDir = "content/en"


# Change single params to "false" to remove from rendering
[params]
  subtitle = "My Personal Website" # This goes in the header and in the site title
  # PAGES
  [params.homepage]
    # Notice that SEO meta tags (what appears in google search results) can be set
    # in individual pages frontmatters `/content/<page>`
    ###
    preTitle = 'My Personal Website'
    title = "Lia Brüggemann"
    # You can use some markdown safely here as long as you don't include line breaks
    intro= """
### "Im Interested in all things Tech, Coding, Media and whatnot"
___

Hi there! I'm Lia, a 20-year-old who's been happily tinkering with all things tech, Linux, and coding for as long as I can remember. This little online space is where I'll be settling in to share the interesting bits and bobs I stumble upon. Pull up a chair and make yourself at home!
        """
    mainButton = "My Projects"
    mainButtonRef = "projects" # Just write the name or slug of the page here
    secondButton = "Contact me"
    secondButtonRef = "contacts" # Just write the name or slug of the page here
    blogButtonRef = "posts"
  # For the blog feed section (visible only if posts are rendered)
    blogTitle = "My Blog Posts"
    blogButton= "Posts"

[params.office]
  title = "Galerie"
 description = "This page can be easily customized by adding a google maps link to get directions towards your activity location."
 buttonText = "Get directions"
 buttonLink = "https://maps.app.goo.gl/LzsPzRkTYSZ8SF3y8" # google maps "share" link here (for button)
 mapLink = "https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d382266.44569392945!2d-76.55832397784323!3d41.53770983690751!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x89c4d93a77484bbb%3A0xfff27920ab9bfae8!2sScranton%2C%20Pennsylvania%2C%20Stati%20Uniti!5e0!3m2!1sit!2sit!4v1716459350324!5m2!1sit!2sit" # google maps "embed" link here

[params.contacts]
  title = "Get in touch!"
  formCallToAction = "Contact me via this Page"
  socialCallToAction = "Here are some of my Socials" # These are the same as in [params.social]
  [params.contacts.form]
    formspreeLink = "https://formspree.io/f/meokjpdn" #subscribe to formspree and add the link for the form here
    firstname = "Firstname*"
    lastname = "Lastname*"
    email = "E-mail*"
    phone = "Phone Number*"
    Inquiry = "Inquiry*"
    checkbox = "I accept that my data will be processed in accordance with the law*"
    submitBtn = "Submit"
[params.services]
  title = "Features"
  description = """ I built this theme with simplicity in mind, it is small and easily customizable, responsive, modular and multilingual. But it also leaves some space to further in-depth customization since it uses Bootstrap and SCSS.
  This page also shows an example of how you can change the site`s page names: The site will use the `services.html` layout for this page, but the page will be called "Features" and the link will use the related permalink `/features`."""
  [params.services.list]
    # You can add as much params.services.list.<N> as you like
    [params.services.list.0]
      title= "Responsive"
      description= "The theme is fully responsive and shows perfectly on every screen size."
    [params.services.list.01]
      title = "Modular"
      description= "Hide and show some elements easily from the config file."
    [params.services.list.02]
      title = "Multilingual"
      description= "The default content language is english (it can be changed), but you can add as many languages as you want very easily, the theme includes an italian language example and a dropdown menù for easily switching between languages. Permalinks can be localized in each language (eg. you can have `/contacts` for english and `/contatti` for italian)."
    [params.services.list.03]
      title = "Customizable"
      description= "The page content can be customized from within the config files."
    [params.services.list.04]
      title = "SEO ready"
      description= "Every page in /content has an easily customizable meta description and a unique meta title for better and easier indexing. The theme will use the image `static/img/meta-image` as meta image for Google, Meta and X."
    [params.services.list.05]
      title = "Google Analytics supported"
      description= "Insert your Google Analytics tag in the `config.toml` file and be ready to track your site performances easily."
    [params.services.list.06]
      title = "Google Maps Included"
      description= "The contact page can be easily customized by adding a google maps link to get directions towards your activity location."

[params.socials]
  enabled = true # enables/disables the whole social section in the footer
  callToAction= "Here are some of my Socials >"
      [[params.socials.link]]
        name = "github"
        link = "https://github.com/BlyDoesCoding"
      [[params.socials.link]]
        name = "linkedin"
        link = "https://linkedin.com/in/lia-brüggemann-b3275b35b"
      [[params.socials.link]]
        name = "code-slash"
        link = "https://dev.to/blydoescoding"
      # You can add other socials here by copypasting the above section and
      # selecting the right name for the icon from here https://icons.getbootstrap.com/

[params.schedules] # Time schedules (eg. your office openming hours)
  enabledFooter = false # This will add the schedules on the footer too
  enabledContacts = true # This will add the schedule to the contact page
  title = "Checking my Mails" # For contacts page only
  [params.schedules.days]
  # Use something like "Monday: 9-13" for each day
  # if left empty it is disabled (default)
    day1 = "Monday: 6pm – 10pm"
    day2 = "Tuesday: 6pm – 10pm"
    day3 = "Wednesday: 6pm – 10pm"
    day4 = "Thursday: 6pm – 10pm"
    day5 = "Friday: 4pm – 6pm"
    day6 = ""
    day7 = ""

[params.footer]
  extraDescription1 = ""
  extraDescription2 = ""
  [params.footer.navigate]
  heading = "Navigate"
  [params.footer.contacts]
  enabled = true # enables/disables the whole contacts section in footer
  heading = "Contact"
  address = ""
  mail = "mail@lia-brueggemann.de"
  mail2 = "coding@blydoesmail.de"
  phone = ""

[params.notfound]
  title = "404, page not found, but we have Tea" # text for 404 page

[params.single] # for posts pages (visible only if posts are rendered)
  similarContent= "Similar Content"
  toc= "Table of Contents"

[menus]
# PageRef should refer to the "translationKey" in `/content/<page>` frontmatter, names can be changed freely
  [[menus.main]]
  name = "Home"
  pageRef = "/"
  weight = 1
  [[menus.main]]
  name = "Projects"
  pageRef = "projects/"
  weight = 2
  [[menus.main]]
  name = "Posts"
  pageRef = "posts/"
  weight = 3
  [[menus.main]]
  name = "Contact"
  pageRef = "pages/contacts"
  weight = 4
